spring:
  application:
    name: posun-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/posun_db
    username: postgres
    password: Chitiva_09
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  # Flyway DEBE ir dentro de spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

# Propiedades personalizadas (Fuera de spring:)
api:
  security:
    token:
      secret: ${JWT_SECRET:1234567890}
      expiration: 86400

logging:
  level:
    root: INFO
    com.posun: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE